[package]
name = "aoc2019"
version = "0.1.0"
edition = "2024"

[dependencies]
array_tool = "1.0.3"
clap = { version = "4.5.36", features = ["derive"] }
itertools = "0.14.0"
nom = "8.0.0"
num = "0.4.3"
regex = "1.11.1"
